#!/bin/sh

if [ "$1" = "-h" ]; then
	echo
	echo "$0"
	echo
	echo "Prints status of batteries"
	echo
	echo "   Will print out the percentage and status."
	echo "$0 -c"
	echo "   Will just print out the percentage with no fansy stuff. Thus it is clean."
	echo "$0 -s"
	echo "   Will just print out the state."
	echo "$0 -h"
	echo "   Will give you this."
	exit 0
fi

for b in `find /sys/devices/ -name "BAT*"`; do
	cd "$b"
	now=`cat energy_now`
	full=`cat energy_full`
	percent=`echo "100 * $now / $full" | bc`
	status=`cat status`

	if [ "$1" = "-c" ]; then
		echo "$percent"
	elif [ "$1" = "-s" ];then
		echo "$status"
	else
		echo "$percent% [$status]"
	fi
done
