#!/bin/sh
# lowbatteryd: starts/stops lowbatteryd daemon

case "$1" in
	start) 
		/usr/bin/lowbatteryd
		;;
	stop) 
		/usr/bin/lowbatteryd --stop
		;;
	restart) 
		$0 stop
		$0 start
		;;
	*) echo "Usage: $0 {start|stop|reload|restart|status}" ; exit 1
esac
exit $?
