#!/bin/bash

MESSAGEFILE="/tmp/lowbatteryd-`find /tmp -name \"lowbatteryd-*\" | wc -l`"
LOW=10
VERYLOW=3

function low {
    showmessage -t 5 "Get To The Power!"
}

function verylow {
    showmessage -t 10 "I'm Gonna Die Soon!"
}

function check {
    DELAY=$1
    if [ -z $DELAY ]; then
        DELAY=20
    fi

    touch "$MESSAGEFILE"

    while :
    do
        MESSAGE=`cat "$MESSAGEFILE"`
        if [ "$MESSAGE" == "STOP" ]; then
            break
        fi

        STATE=`battery -s`
        if [ "$STATE" == "Charging" ]; then
            MESSAGE="CHARGING"
            cat /dev/null > "$MESSAGEFILE"
            continue
        fi

        BATTERY=`battery -c`
        if [ $BATTERY -lt $VERYLOW ] && [ "$MESSAGE" != "VERYLOW" ] && [ "$MESSAGE" != "CHARGING" ]; then
            verylow
            echo "VERYLOW" > "$MESSAGEFILE"
        elif [ $BATTERY -lt $LOW ] && [ -z "$MESSAGE" ]; then
            low
            echo "LOW" > "$MESSAGEFILE"
        fi

        sleep $DELAY
    done

    rm "$MESSAGEFILE"
    echo "Stopped lowbatteryd"
}

if [ "$1" == "-h" ]; then
    echo "$0 [n]"
    echo "   Will check the battery percentage every n (20 if not given) seconds. If it is below $LOW% it will show a message, if below $VERYLOW% a different message."
    echo "$0 --stop"
    echo "   Will stop the daemon."
    echo "$0 -h"
    echo "   Will give you this."
elif [ "$1" == "--stop" ]; then
    echo "STOP" > "$MESSAGEFILE"
else
    check "$1"
fi
